version: 2

project_name: papra-imap

before:
  hooks:
    - go mod tidy

builds:
  - id: papra-imap
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

kos:
  - id: papra-imap
    build: papra-imap
    repository: ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap
    base_image: gcr.io/distroless/base-debian12
    tags:
      - "{{ .Tag }}"
      - latest
    bare: true
    platforms:
      - linux/amd64
      - linux/arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
