version: 2

project_name: papra-imap

before:
  hooks:
    - go mod tidy

builds:
  - id: papra-imap
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - ids:
      - papra-imap
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap:{{ .Tag }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - ids:
      - papra-imap
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap:{{ .Tag }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/papra-imap:{{ .Tag }}-arm64"

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
